<template>
  <div id="app">
    <picture>
      <source
        srcset="@/assets/trianglify.svg"
        type="image/svg+xml"
        alt="createur-de-site-internet sur mesure beaujolais oingt"
      />
      <img
        class="fondecran"
        src="@/assets/trianglify.png"
        alt="createur-de-site-internet sur mesure beaujolais oingt"
      />
    </picture>
    <menue></menue>

    <PageHeader />
    <transition name="slide-out-elliptic-top-fwd" mode="out-in">
      <router-view :key="$route.fullPath"></router-view>
    </transition>

    <PageFooter />
  </div>
</template>

<script>
import menue from "./components/menu.vue";
import PageHeader from "./components/PageHeader.vue";
import PageFooter from "./components/PageFooter.vue";
export default {
  name: "app",
  components: {
    PageHeader,
    PageFooter,
    menue
  }
};
</script>

<style>
.fondecran {
  position: fixed;
  margin: 0;
  padding: 0;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  z-index: 0;
}

.slide-out-elliptic-top-fwd-enter-active {
  animation-delay: 0.5s;
  opacity: 1;
}
.slide-out-elliptic-top-fwd-leave-active {
  -webkit-animation: slide-out-elliptic-right-bck 0.3s ease-in both;
  animation: slide-out-elliptic-right-bck 0.3s ease-in both;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-2-2 18:45:41
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-elliptic-top-fwd
 * ----------------------------------------
 */
/* ----------------------------------------------
 * Generated by Animista on 2019-2-2 19:3:12
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-elliptic-right-bck
 * ----------------------------------------
 */
@-webkit-keyframes slide-out-elliptic-right-bck {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
    transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: -1800px 50%;
    transform-origin: -1800px 50%;
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px) rotateY(-30deg) scale(0);
    transform: translateX(1000px) rotateY(-30deg) scale(0);
    -webkit-transform-origin: -100% 50%;
    transform-origin: -100% 50%;
    opacity: 1;
  }
}
@keyframes slide-out-elliptic-right-bck {
  0% {
    -webkit-transform: translateX(0) rotateY(0) scale(1);
    transform: translateX(0) rotateY(0) scale(1);
    -webkit-transform-origin: -1800px 50%;
    transform-origin: -1800px 50%;
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px) rotateY(-30deg) scale(0);
    transform: translateX(1000px) rotateY(-30deg) scale(0);
    -webkit-transform-origin: -100% 50%;
    transform-origin: -100% 50%;
    opacity: 1;
  }
}
</style>
